version: '3'

services:
  site:
    build:
      context: .
      dockerfile: nginx.dockerfile
    user: root
    container_name: nginx_gpt
    ports:
      - "5007:80"
    volumes:
      - ./dist:/var/www/html:delegated

